### ISSUE TITLE
Functions can build and then panic despite being marked no_panic

### ISSUE THREAD

**Issue by Lokathor** [dtolnay/no-panic#12]
I was just checking that `no_panic` was working so I put an [explicit panic](https://github.com/Lokathor/imagine/blob/allocate-less-fuzz-more/src/png/zlib.rs#L60-L65) into a function being tested. It builds and then panics [on windows](https://ci.appveyor.com/project/Lokathor/imagine-mgo2s/builds/29547054/job/gftj3400y09xbs08), [linux](https://travis-ci.org/Lokathor/imagine/jobs/625229645?utm_medium=notification&utm_source=github_status), and [Mac](https://travis-ci.org/Lokathor/imagine/jobs/625229646?utm_medium=notification&utm_source=github_status).

**Comment by danielhenrymantilla** [comment]
I think this has more to do with `#[cfg_attr(test, ...)]` and how it interacts with builds

**Comment by dtolnay** [comment]
`cfg_attr(test, no_panic)` is not what you want. Take a look at how https://github.com/dtolnay/ryu does it.

This is the following caveat from the readme:

> Panic detection happens at link time across the entire dependency graph, so any Cargo commands that do not invoke a linker will not trigger panic detection. This includes `cargo build` of library crates and `cargo check` of binary and library crates.

When you run `cargo test` it builds your crate in cfg(not(test)) mode for integration tests, so the no_panic attribute is not present when your `check_test3x3png` test invokes `decompress`.

**Comment by Lokathor** [comment]
this is unfortunate news because i learned about doing it with cfg_attr(test) via libm

**Comment by danielhenrymantilla** [comment]
I guess a warning against this pattern could be added to the docs ?

**Comment by Lokathor** [comment]
Yeah, libm [uses this](https://github.com/rust-lang/libm/blob/master/src/math/acos.rs#L62):
```rust
#[cfg_attr(all(test, assert_no_panic), no_panic::no_panic)]
```
Which looks like it'd have the same problem I guess?

---

@dtolnay Looking at `ryu`, it looks like the suggested path is to have it controlled via feature, and then activate the feature during tests and/or builds?

**Comment by dtolnay** [comment]
Libm is fine because they use unit tests, not integration tests. Unit tests build the crate in cfg(test) mode.

**Comment by dtolnay** [comment]
I'll close this in favor of #8 which tracks adding better documentation of the best practices and edge cases.
