### ISSUE TITLE
enabling in release-only or using feature

### ISSUE THREAD

**Issue by jadamcrain** [dtolnay/no-panic#13]
" either make no-panic an optional dependency that you only enable in release builds"

Being fairly new to `cfg_attr` and the like, what's the best way to accomplish this?

**Comment by dtolnay** [comment]
The ryu crate at https://github.com/dtolnay/ryu demonstrates this approach.

- https://github.com/dtolnay/ryu/blob/d8b530f84dd4766a99acc3bd514052be1e3006ca/Cargo.toml#L20
- https://github.com/dtolnay/ryu/blob/d8b530f84dd4766a99acc3bd514052be1e3006ca/.travis.yml#L8

**Comment by jadamcrain** [comment]
you rock. Thanks. What a great tool.
