### ISSUE TITLE
Could we extend no-panic to work on blocks, not just functions?

### ISSUE THREAD

**Issue by rw** [dtolnay/no-panic#14]
It would be nice to have this macro work on blocks, not just named functions. One concrete use case is that a function may panic, but inside its body, after making some assertions to set up preconditions, an inner block may be `no_panic`.

**Comment by rw** [comment]
I see that this requires the unstable features `stmt_expr_attributes` and/or `proc_macro_hygiene`. It still would be useful, though.

**Comment by dtolnay** [comment]
Sure thing, I would accept a PR to implement this.

**Comment by rw** [comment]
@dtolnay Cool! Do you think the design needs to change for this use case, or would it use the same reasoning as in your [case study](https://github.com/dtolnay/case-studies/tree/master/function-epilogue)? My understanding is that implementing it on blocks might be simpler than implementing it on functions.

**Comment by dtolnay** [comment]
I don't have an implementation specifically in mind. I suspect implementing blocks would be harder than functions because we don't have a "signature" to work with i.e. what the inputs and outputs of the block might be.

**Comment by rw** [comment]
The bigger issue I'm trying to solve is that I can't seem to get Vec `push` to be no_panic, even if I assert preconditions on the length and capacity. Is that something you know about already? Happy to discuss it in a separate issue.

**Comment by dtolnay** [comment]
Closing because I don't plan to dedicate time to this, but if someone submits a PR with a working implementation, I could consider it.
