### ISSUE TITLE
Idea: add can_panic macro

### ISSUE THREAD

**Issue by rw** [dtolnay/no-panic#17]
I find that when I use `no_panic` in a crate, I end up learning more about which of my functions *can* panic.

For me, this typically occurs when I forget that allocations can fail, so my function can't be annotated with `no_panic`.

In my workflow, after I think through this reasoning, I want to annotate the function with information that informs the reader that I *did* try to annotate with `no_panic`, but that my attempt failed because the function may actually panic.

To this end, I suggest a no-op annotation called `can_panic` as a complement to `no_panic`.

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate. A "no-op annotation" is what comments are for (whether that be a doc comment or an ordinary comment).

Standard library documentation has a convention of using a `# Panics` section in rustdoc to indicate all the panicking conditions. https://rust-lang.github.io/api-guidelines/documentation.html#c-failure
