### ISSUE TITLE
Adding tests for async calls

### ISSUE THREAD

**Issue by paulkass** [dtolnay/no-panic#21]
Hey all, I'm trying to see if this macro would work on `async` functions. In order to do that, i want to add a test in my fork and work from there. Since the function is async, I need a runtime like `tokio` to run it. However, it seems like the tests include `no_panic` without including any other external libs. Should I repeatedly add all of the `.rlib` files in `target/debug/deps` with `--extern` options to the test `rustc` command? That didn't really seem to work. 

Was wondering if anyone has advice on how to include a lib like `tokio` in a coherent way into the test runs of `rustc`. Thanks!

**Comment by dtolnay** [comment]
Sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community.
