### ISSUE TITLE
Detected panic when returning a String

### ISSUE THREAD

**Issue by paulkass** [dtolnay/no-panic#22]
When returning a method returns a string, the `no_panic` linking fails even though the function is not necessarily panicking. So for example take this code in `src/bin.rs`:

```
#[no_panic] 
fn help() -> String { String::from("wow") }

#[no_panic] 
fn help2() -> &'static str { "wow" }
```

When running the first one, linking fails with this error: 
```
in function `<no_panic_playground::help::__NoPanic as core::ops::drop::Drop>::drop':
          .../src/main.rs:23: undefined reference to `

          ERROR[no-panic]: detected panic in function `help`
          '
          collect2: error: ld returned 1 exit status
```

The second function runs fine. Wondering if this is a known issue.

**Comment by dtolnay** [comment]
It looks like that does have a panic codepath, so no_panic is behaving correctly.

`String::from` calls `str::to_owned`:
- https://github.com/rust-lang/rust/blob/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/string.rs#L2309

calls `<[_]>::to_owned`:
- https://github.com/rust-lang/rust/blob/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/str.rs#L205

calls `<[_]>::to_vec`:
- https://github.com/rust-lang/rust/blob/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/slice.rs#L726

calls `alloc::slice::hack::to_vec`:
- https://github.com/rust-lang/rust/blob/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/slice.rs#L393

calls `Vec::extend_from_slice`:
- https://github.com/rust-lang/rust/blob/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/slice.rs#L158

calls `Vec::spec_extend`:
- https://github.com/rust-lang/rust/blob/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/vec.rs#L1591

calls `Vec::reserve`:
- https://github.com/rust-lang/rust/blob/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/vec.rs#L2136

calls `RawVec::reserve`:
- https://github.com/rust-lang/rust/blob/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/vec.rs#L505

calls `alloc::raw_vec::capacity_overflow`:
- https://github.com/rust-lang/rust/blob/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/raw_vec.rs#L301

calls `panic!`:
- https://github.com/rust-lang/rust/blob/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/raw_vec.rs#L535

It should work if you use lto to optimize that stuff out.

```toml
# Cargo.toml

[profile.release]
lto = true
```

**Comment by paulkass** [comment]
Wondering how you got this path-to-panic? Is there a specific tool that you used, or did you manually search through the code?
