### ISSUE TITLE
no_release_panic and more

### ISSUE THREAD

**Issue by leonardo-m** [dtolnay/no-panic#27]
I think an improved version of this no_panic is worth having in the core Rust language instead of in an external crate because I think this attribute goes very well with the correctness purposes of Rust language. By improved version I meant with a cleaner error message, and perhaps working recursively (requiring a function to call other no_panic functions)?

Perhaps beside the `#[no_panic]` is also worth having `#[no_release_panic]` that tests for the presence of panics only when the function is compiled in release mode.

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate.
