### ISSUE TITLE
Another way to disable panics

### ISSUE THREAD

**Issue by safinaskar** [dtolnay/no-panic#65]
Hi. I found another way of creating undroppable types: https://jack.wrenn.fyi/blog/undroppable/ . This method can be used to prevent panics. This will enable us to detect panics at compile stage (not at linking stage) and will free us from LTO requirement and other tricks

**Comment by dtolnay** [comment]
It is not useful for this purpose as discussed in https://www.reddit.com/r/rust/s/0NRjxtvXzs.
