### ISSUE TITLE
no_panic and const

### ISSUE THREAD

**Issue by BenjaminBrienen** [dtolnay/no-panic#66]
Does `no_panic` work with const functions? If not, It should be mentioned in the documentation, I think.

```rs
error[E0015]: cannot call non-const closure in constant functions
   --> crates\bevy_math\src\rotation2d.rs:224:5
    |
224 |     #[no_panic]
    |     ^^^^^^^^^^^
    |
    = note: closures need an RFC before allowed to be called in constant functions
    = note: calls in constant functions are limited to constant functions, tuple structs and tuple variants
    = note: this error originates in the attribute macro `no_panic` (in Nightly builds, run with -Z macro-backtrace for more info)
```
```rs
    #[no_panic]
    pub const fn sin_cos(self) -> (f32, f32) {
        (self.sin, self.cos)
    }
```

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Updated the README.md to include a note in the Caveats section mentioning that no_panic does not work with const functions. This addresses the issue described in the criteria.

You can review changes in this commit: https://github.com/wwqwq2313/dtolnay-no-panic-66/commit/cb56ed128ceb741e72e59f640098355037db5e2b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
