### ISSUE TITLE
Strange borrow checker error

### ISSUE THREAD

**Issue by RazrFalcon** [dtolnay/no-panic#7]
[This code](https://github.com/RazrFalcon/xmlparser/blob/0c57d68e57086e3d4afd59325dc55fa6083f10dc/src/stream.rs#L326..L339) produces such error:

```rust
error[E0382]: use of moved value: `*self`
   --> src/stream.rs:331:26
    |
326 |     #[no_panic]
    |     ----------- value moved here
...
331 |                     vec![self.curr_byte_unchecked(), c],
    |                          ^^^^ value used here after move
    |
    = note: move occurs because `self` has type `&mut stream::Stream<'a>`, which does not implement the `Copy` trait
```

You can test it in [this branch](https://github.com/RazrFalcon/xmlparser/tree/no-panic-demo).

Probably the same issue as in the https://github.com/dtolnay/no-panic/issues/1

**Comment by dtolnay** [comment]
Thanks! I released no-panic 0.1.8 with a fix. This was a bug related to `self` being used inside of a macro invocation like `vec!`.
